/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LogoRouteImport } from './routes/logo'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CraftsListRouteImport } from './routes/crafts/list'
import { Route as CraftsDitherRouteImport } from './routes/crafts/dither'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoRoute = LogoRouteImport.update({
  id: '/logo',
  path: '/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsListRoute = CraftsListRouteImport.update({
  id: '/crafts/list',
  path: '/crafts/list',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsDitherRoute = CraftsDitherRouteImport.update({
  id: '/crafts/dither',
  path: '/crafts/dither',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/logo': typeof LogoRoute
  '/projects': typeof ProjectsRoute
  '/crafts/dither': typeof CraftsDitherRoute
  '/crafts/list': typeof CraftsListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/logo': typeof LogoRoute
  '/projects': typeof ProjectsRoute
  '/crafts/dither': typeof CraftsDitherRoute
  '/crafts/list': typeof CraftsListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/logo': typeof LogoRoute
  '/projects': typeof ProjectsRoute
  '/crafts/dither': typeof CraftsDitherRoute
  '/crafts/list': typeof CraftsListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/logo'
    | '/projects'
    | '/crafts/dither'
    | '/crafts/list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog' | '/logo' | '/projects' | '/crafts/dither' | '/crafts/list'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/logo'
    | '/projects'
    | '/crafts/dither'
    | '/crafts/list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  LogoRoute: typeof LogoRoute
  ProjectsRoute: typeof ProjectsRoute
  CraftsDitherRoute: typeof CraftsDitherRoute
  CraftsListRoute: typeof CraftsListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo': {
      id: '/logo'
      path: '/logo'
      fullPath: '/logo'
      preLoaderRoute: typeof LogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafts/list': {
      id: '/crafts/list'
      path: '/crafts/list'
      fullPath: '/crafts/list'
      preLoaderRoute: typeof CraftsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafts/dither': {
      id: '/crafts/dither'
      path: '/crafts/dither'
      fullPath: '/crafts/dither'
      preLoaderRoute: typeof CraftsDitherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  LogoRoute: LogoRoute,
  ProjectsRoute: ProjectsRoute,
  CraftsDitherRoute: CraftsDitherRoute,
  CraftsListRoute: CraftsListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
